Update rephrase
deepin-community/rephrase pull request #1
Opened 2023-06-30 09:00 UTC by Diamond-Fur

https://github.com/deepin-community/sig-deepin-sysdev-team/issues/31

2023-06-30 09:02 UTC, xzl01 requested changes
debian/deepin 文件夹不存在

2023-06-30 09:02 UTC, xzl01 commented
.github文件夹不存在

2023-07-03 02:49 UTC, Zeno-sole commented
.debhelper是构建过程中的产物 应该删除

2023-07-03 03:48 UTC, Zeno-sole commented
/approve

2023-07-03 03:49 UTC, merged